[build]
  functions = "functions"
  publish   = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
